Drop table Record, FineType, Employee, Office, DriversGroups, Vehicle, LicenseGroup, Driver

-- Generated by Oracle SQL Developer Data Modeler 17.3.0.261.1529
--   at:        2018-11-03 09:58:51 CET
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Driver 
    (
     ID INTEGER NOT NULL IDENTITY, 
     Name VARCHAR (100) NOT NULL , 
     Street VARCHAR (100) NOT NULL , 
     Town VARCHAR (100) NOT NULL , 
     Country VARCHAR (100) NOT NULL , 
     Residence VARCHAR (50) NOT NULL , 
     BirthDate DATE NOT NULL , 
     RemainingPoints INTEGER NOT NULL , 
     LicenseNumber INTEGER NOT NULL , 
     LicenseValidity DATE NOT NULL , 
     State BIT NOT NULL , 
     Password VARCHAR (100) NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Driver ADD CONSTRAINT Driver_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE DriversGroups 
    (
     driverID INTEGER NOT NULL , 
     groupID INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE DriversGroups ADD CONSTRAINT DriversGroups_PK PRIMARY KEY CLUSTERED (driverID, groupID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Employee 
    (
     ID INTEGER NOT NULL IDENTITY, 
     Name VARCHAR (100) NOT NULL , 
     Rank VARCHAR (100) NOT NULL , 
     officeID INTEGER NOT NULL , 
     State BIT NOT NULL , 
     Password VARCHAR (100) NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Employee ADD CONSTRAINT Employee_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE FineType 
    (
     ID INTEGER NOT NULL IDENTITY, 
     Category VARCHAR (50) NOT NULL , 
     Description VARCHAR (1000) NOT NULL , 
     MaxFine INTEGER NOT NULL , 
     PointsPenalty INTEGER NOT NULL , 
     State BIT NOT NULL 
    )
    ON "default"
GO

ALTER TABLE FineType ADD CONSTRAINT FineType_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE LicenseGroup 
    (
     ID INTEGER NOT NULL IDENTITY, 
     "Group" VARCHAR (5) NOT NULL , 
     Description VARCHAR (500) NOT NULL 
    )
    ON "default"
GO

ALTER TABLE LicenseGroup ADD CONSTRAINT LicenseGroup_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Office 
    (
     ID INTEGER NOT NULL IDENTITY, 
     Street VARCHAR (100) NOT NULL , 
     Town VARCHAR (100) NOT NULL , 
     Country VARCHAR (100) NOT NULL , 
     Type VARCHAR (100) NOT NULL , 
     State BIT NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Office ADD CONSTRAINT Office_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

CREATE TABLE Record 
    (
     ID INTEGER NOT NULL IDENTITY, 
     Ammount INTEGER NOT NULL , 
     PointsTaken INTEGER NOT NULL , 
     DateOfEntry DATE NOT NULL , 
     ExpireDate DATE NOT NULL , 
     PaidDate DATE , 
     driverID INTEGER NOT NULL , 
     employeeID INTEGER NOT NULL , 
     fineTypeID INTEGER NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Record ADD CONSTRAINT Record_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO


CREATE TABLE Vehicle 
    (
     ID INTEGER NOT NULL IDENTITY, 
     VIN VARCHAR (100) NOT NULL , 
     SPZ VARCHAR (10) NOT NULL , 
     Brand VARCHAR (100) NOT NULL , 
     Model VARCHAR (100) NOT NULL , 
     Type VARCHAR (100) NOT NULL , 
     Color VARCHAR (100) NOT NULL , 
     driverID INTEGER NOT NULL , 
     State BIT NOT NULL 
    )
    ON "default"
GO

ALTER TABLE Vehicle ADD CONSTRAINT Vehicle_PK PRIMARY KEY CLUSTERED (ID)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO

ALTER TABLE DriversGroups 
    ADD CONSTRAINT DriversGroups_Driver_FK FOREIGN KEY 
    ( 
     driverID
    ) 
    REFERENCES Driver 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DriversGroups 
    ADD CONSTRAINT DriversGroups_LicenseGroup_FK FOREIGN KEY 
    ( 
     groupID
    ) 
    REFERENCES LicenseGroup 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Employee 
    ADD CONSTRAINT Employee_Office_FK FOREIGN KEY 
    ( 
     officeID
    ) 
    REFERENCES Office 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Record 
    ADD CONSTRAINT Record_Driver_FK FOREIGN KEY 
    ( 
     driverID
    ) 
    REFERENCES Driver 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Record 
    ADD CONSTRAINT Record_Employee_FK FOREIGN KEY 
    ( 
     employeeID
    ) 
    REFERENCES Employee 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Record 
    ADD CONSTRAINT Record_FineType_FK FOREIGN KEY 
    ( 
     fineTypeID
    ) 
    REFERENCES FineType 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Vehicle 
    ADD CONSTRAINT Vehicle_Driver_FK FOREIGN KEY 
    ( 
     driverID
    ) 
    REFERENCES Driver 
    ( 
     ID 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
